In [8]:
#import libraries
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [9]:
data=pd.read_csv('iphone.csv')

In [11]:
data

Gender  Age  Salary  Purchase Iphone
0      Male   19   19000                0
1      Male   35   20000                0
2    Female   26   43000                0
3    Female   27   57000                0
4      Male   19   76000                0
..      ...  ...     ...              ...
395  Female   46   41000                1
396    Male   51   23000                1
397  Female   50   20000                1
398    Male   36   33000                0
399  Female   49   36000                1

[400 rows x 4 columns]

In [15]:
data.isnull().sum()

Gender             0
Age                0
Salary             0
Purchase Iphone    0
dtype: int64

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64 
 2   Salary           400 non-null    int64 
 3   Purchase Iphone  400 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 12.6+ KB


In [18]:
# seperate data into x and y 
x=data.iloc[:,:-1].values
y=data.iloc[:,3].values

In [20]:
x

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [21]:
# label encoder 
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])

In [22]:
x

array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       ...,
       [0, 50, 20000],
       [1, 36, 33000],
       [0, 49, 36000]], dtype=object)

In [93]:
# split the data into train and test 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [94]:
x_train

array([[0, 44, 39000],
       [1, 32, 120000],
       [0, 38, 50000],
       [0, 32, 135000],
       [0, 52, 21000],
       [0, 53, 104000],
       [1, 39, 42000],
       [1, 38, 61000],
       [0, 36, 50000],
       [0, 36, 63000],
       [0, 35, 25000],
       [1, 35, 50000],
       [1, 42, 73000],
       [0, 47, 49000],
       [0, 59, 29000],
       [1, 49, 65000],
       [0, 45, 131000],
       [0, 31, 89000],
       [0, 46, 82000],
       [0, 47, 51000],
       [1, 26, 15000],
       [1, 60, 102000],
       [0, 38, 112000],
       [1, 40, 107000],
       [0, 42, 53000],
       [1, 35, 59000],
       [1, 48, 41000],
       [0, 48, 134000],
       [0, 38, 113000],
       [1, 29, 148000],
       [0, 26, 15000],
       [1, 60, 42000],
       [1, 24, 19000],
       [1, 42, 149000],
       [0, 46, 96000],
       [1, 28, 59000],
       [1, 39, 96000],
       [1, 28, 89000],
       [1, 41, 72000],
       [1, 45, 26000],
       [0, 33, 69000],
       [0, 20, 82000],
       [1, 31, 74000],


In [95]:
# applying scaler 
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
x_train=SC.fit_transform(x_train)
x_test=SC.fit_transform(x_test)

In [96]:
x_test

array([[ 1.02020406, -0.54748976,  0.5130727 ],
       [-0.98019606,  0.15442019, -0.61825566],
       [ 1.02020406, -0.10879604,  0.14615539],
       [-0.98019606, -0.54748976,  0.26846116],
       [-0.98019606, -0.10879604, -0.61825566],
       [ 1.02020406, -0.81070599, -1.53554892],
       [-0.98019606, -0.45975102, -1.68843113],
       [ 1.02020406, -0.0210573 ,  2.25592989],
       [-0.98019606, -1.60035469, -0.0678797 ],
       [ 1.02020406,  0.94406888, -0.83229075],
       [ 1.02020406, -0.54748976, -0.6488321 ],
       [-0.98019606, -0.72296725, -0.46537345],
       [ 1.02020406,  0.06668145, -0.46537345],
       [ 1.02020406,  0.24215893,  0.20730828],
       [ 1.02020406, -1.4248772 ,  0.48249625],
       [-0.98019606, -0.37201227,  1.43036596],
       [ 1.02020406,  0.06668145,  0.20730828],
       [ 1.02020406, -1.51261594,  0.45191981],
       [-0.98019606,  1.64597884,  1.8278597 ],
       [ 1.02020406, -0.10879604, -1.47439603],
       [-0.98019606, -0.10879604, -0.709

In [97]:
#apply SVM
from sklearn.svm import SVC
Class=SVC()
Class.fit(x_train,y_train)

SVC()

In [98]:
y_pred=Class.predict(x_test)

In [99]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [100]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [101]:
# EVALUATE the performance of svm model 
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[64  4]
 [ 3 29]]


In [102]:
#performance measure => accuracy
from sklearn.metrics import accuracy_score
AS= accuracy_score(y_test,y_pred)
print(AS)

0.93


In [103]:
# classification report 
from sklearn.metrics import classification_report 
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.94      0.95        68
           1       0.88      0.91      0.89        32

    accuracy                           0.93       100
   macro avg       0.92      0.92      0.92       100
weighted avg       0.93      0.93      0.93       100



# Naive Bayes algorithm same iphone dataset  

In [104]:
#Naive bayes classifier 
from sklearn.naive_bayes import GaussianNB

In [105]:
classifier = GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [106]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [107]:
# to evaluate the performance of the model 
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score
print(confusion_matrix(y_test,y_pred))

[[64  4]
 [ 5 27]]


In [108]:
print(accuracy_score(y_test,y_pred))

0.91


In [109]:
# precision =tp/(tp+fp)
print(precision_score(y_test,y_pred))

0.8709677419354839


In [110]:
# save the model
import joblib 
joblib.dump(classifier,'Naive_bayes.sav')

['Naive_bayes.sav']