In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sea

In [2]:
df=pd.read_csv('User_data.csv')
df.sample(10)

User ID  Gender  Age  EstimatedSalary  Purchased
254  15724161  Female   50            44000          0
225  15622171    Male   37            53000          0
291  15596522    Male   49            89000          1
296  15673539    Male   42            73000          1
130  15675185    Male   31            58000          0
374  15793890  Female   37            80000          0
276  15734312    Male   38            71000          0
341  15776844    Male   35            75000          0
357  15671387  Female   41            72000          0
345  15716781  Female   41            63000          0

In [9]:
# we are predicting the user will purchase the company's newly launched product or not 

In [10]:
# check if there are null values
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [11]:
# check all info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [13]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [15]:
# get the count of label 0 & 1
df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [17]:
#divide data into dependent(y) and independent(x)
x = df.iloc[:,[2,3]].values
y = df.iloc[:,4].values

In [92]:
# split the data into train and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [93]:
x_train

array([[    57, 122000],
       [    39,  71000],
       [    47,  25000],
       [    24,  19000],
       [    36,  50000],
       [    32, 150000],
       [    48,  29000],
       [    30, 107000],
       [    60,  34000],
       [    38,  61000],
       [    33,  31000],
       [    39,  71000],
       [    55,  39000],
       [    49,  39000],
       [    43, 112000],
       [    27,  20000],
       [    26,  17000],
       [    37,  93000],
       [    42,  54000],
       [    35,  61000],
       [    29,  75000],
       [    38,  80000],
       [    45,  26000],
       [    54, 108000],
       [    46,  23000],
       [    23,  28000],
       [    37,  75000],
       [    42,  65000],
       [    35,  71000],
       [    51, 146000],
       [    39,  96000],
       [    24,  89000],
       [    58,  95000],
       [    25,  22000],
       [    41,  59000],
       [    28,  89000],
       [    42,  80000],
       [    42, 108000],
       [    46,  96000],
       [    47, 113000],


In [94]:
x_test

array([[    46,  22000],
       [    59,  88000],
       [    28,  44000],
       [    48,  96000],
       [    29,  28000],
       [    30,  62000],
       [    47, 107000],
       [    29,  83000],
       [    40,  75000],
       [    42,  65000],
       [    35,  65000],
       [    53,  34000],
       [    23,  48000],
       [    20,  23000],
       [    30,  87000],
       [    35, 108000],
       [    52,  38000],
       [    46,  74000],
       [    39,  42000],
       [    56,  60000],
       [    22,  27000],
       [    29,  80000],
       [    47,  23000],
       [    59,  76000],
       [    19,  19000],
       [    51,  23000],
       [    42,  80000],
       [    37,  53000],
       [    55, 125000],
       [    19,  21000],
       [    46,  41000],
       [    19,  70000],
       [    36, 144000],
       [    28,  79000],
       [    40, 107000],
       [    35,  75000],
       [    37,  55000],
       [    38,  65000],
       [    26,  30000],
       [    18,  68000],


In [95]:
from sklearn.preprocessing import StandardScaler

In [96]:
SC=StandardScaler()

In [97]:
x_train=SC.fit_transform(x_train)

In [98]:
x_test=SC.fit_transform(x_test)

In [99]:
x_test

array([[ 0.75872215, -1.41078892],
       [ 1.9109871 ,  0.5590031 ],
       [-0.83672162, -0.75419158],
       [ 0.93599368,  0.79776576],
       [-0.74808586, -1.23171691],
       [-0.65945009, -0.21697557],
       [ 0.84735791,  1.12606443],
       [-0.74808586,  0.40977643],
       [ 0.22690756,  0.17101376],
       [ 0.40417909, -0.12743957],
       [-0.21627127, -0.12743957],
       [ 1.37917251, -1.05264491],
       [-1.27990045, -0.63481024],
       [-1.54580774, -1.38094358],
       [-0.65945009,  0.52915776],
       [-0.21627127,  1.15590977],
       [ 1.29053674, -0.93326358],
       [ 0.75872215,  0.14116843],
       [ 0.13827179, -0.81388224],
       [ 1.6450798 , -0.27666624],
       [-1.36853621, -1.26156225],
       [-0.74808586,  0.32024043],
       [ 0.84735791, -1.38094358],
       [ 1.9109871 ,  0.20085909],
       [-1.63444351, -1.50032492],
       [ 1.20190098, -1.38094358],
       [ 0.40417909,  0.32024043],
       [-0.03899974, -0.48558358],
       [ 1.55644404,

In [100]:
type(x_train)

numpy.ndarray

In [101]:
x_train=pd.DataFrame(x_train,columns=['Age','Salary'])
x_test= pd.DataFrame(x_test,columns=['Age','Salary'])

In [102]:
x_train

Age    Salary
0    1.892589  1.521894
1    0.125038  0.032132
2    0.910616 -1.311575
3   -1.347922 -1.486841
4   -0.169554 -0.581299
..        ...       ...
295 -1.347922 -1.253153
296 -1.151527 -1.019465
297  0.517827  1.843215
298  0.125038  0.207398
299 -0.562343  0.470297

[300 rows x 2 columns]

In [103]:
# training logistic reression model 
from sklearn.linear_model import LogisticRegression

In [104]:
LR=LogisticRegression()

In [105]:
LR.fit(x_train,y_train)

LogisticRegression()

In [106]:
y_pred=LR.predict(x_test)

In [107]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [108]:
y_test

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1], dtype=int64)

In [109]:
#Confusion matrix
#it is a matrix that summarizes the performance of a machine learning 
from sklearn.metrics import confusion_matrix
CM=confusion_matrix(y_pred,y_test)

In [110]:
CM

array([[61, 12],
       [ 2, 25]], dtype=int64)

In [111]:
#performance measure => accuracy
from sklearn.metrics import accuracy_score,classification_report
AS= accuracy_score(y_pred,y_test)
print('The accuracy of our logistic regression model is :',AS)

The accuracy of our logistic regression model is : 0.86


In [112]:
# classification report 
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.97      0.84      0.90        73
           1       0.68      0.93      0.78        27

    accuracy                           0.86       100
   macro avg       0.82      0.88      0.84       100
weighted avg       0.89      0.86      0.87       100



In [115]:
pip install -U textblob

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement textblob (from versions: none)
ERROR: No matching distribution found for textblob
